version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: HackMe228
    ports:
      - "5433:5432"

  app:
    build: .
    image: myapp-image:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bank
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: HackMe228
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      LOGGING_FILE_PATH: .
      LOGGING_FILE_NAME: app.log
    depends_on:
      - db
    ports:
      - "8080:8080"
